version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:

  mongodb:  
    image: mongo # specify image to build container from
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017" # specify port forewarding
#    command: --smallfiles --rest --auth    
    